/*
 * Copyright 2026 Clyde Gerber
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.javai18n.core;

import java.util.EventListener;
import java.util.EventObject;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * An interface to identify classes whose behavior can be localized.
 */
public interface Localizable
{
    /**
     * Get the current Locale for ResourceBundles provided by the object. A more natural name for this method
     * would be getLocale(), but a method by that name already exists in many of the UI components that are
     * good candidates for this interface and the method is often called in the constructor of those objects so
     * overriding it is problematic.
     *
     * @return The Locale for ResourceBundles provided by the object.
     */
    public Locale getBundleLocale();

    /**
     * Set the current Locale for ResourceBundles provided by the object. A more natural name for this method
     * would be setLocale(), but a method by that name already exists in many of the UI components that are
     * good candidates for this interface and the method is often called in the constructor of those objects so
     * overriding it is problematic.
     *
     * @param locale The intended Locale for ResourceBundles provided by the object.
     * @throws dev.javai18n.core.NoCallbackRegisteredForModuleException if no callback has been registered for the module.
     */
    public void setBundleLocale(Locale locale);

    /**
     * Returns the Locales supported by the object.
     *
     * @return The Locales supported by the object.
     */
    Locale[] getAvailableLocales();

    /**
     * Returns the ResourceBundle for the object according to its locale.
     *
     * @return The ResourceBundle for the object according to its locale.
     * @throws dev.javai18n.core.NoCallbackRegisteredForModuleException if no callback has been registered for the module.
     */
    public ResourceBundle getResourceBundle();

    /**
     * LocaleEvents are generated by Localizable objects when their Locale
     * changes.
     */
    public final class LocaleEvent extends EventObject
    {
        private static final long serialVersionUID = 1L;
        /**
         * Constructs a LocaleEvent object given a Localizable source.
         *
         * @param source A Localizable object.
         */
        public LocaleEvent(Localizable source)
        {
            super(source);
        }

        /**
         * Gets the Localizable source of the LocaleEvent.
         *
         * @return The Localizable source of the LocaleEvent.
         */
        public Localizable getLocalizableSource()
        {
            return (Localizable) getSource();
        }
    }

    /**
     * An interface for listeners of LocaleEvents.
     */
    public interface LocaleEventListener extends EventListener
    {
        /**
         * Process the LocaleEvent.
         *
         * @param event A LocaleEvent raised by a Localizable object.
         */
        void processLocaleEvent(LocaleEvent event);
    }

    /**
     * Register LocaleEventListeners.
     *
     * @param listener A LocaleEventListener that is to be notified when
     *        the Localizable object updates its Locale.
     */
    public void addLocaleEventListener(LocaleEventListener listener);

    /**
     * Unregister LocaleEventListeners.
     *
     * @param listener A LocaleEventListener that is no longer to be notified
     *                 when the Localizable object updates its Locale.
     */
    public void removeLocaleEventListener(LocaleEventListener listener);
}
